[package]
name = "linq-first-step-expression"
version = "0.1.0"
authors = ["Dmitry Demin <shepardiwe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
